### ISSUE TITLE
How about connecting with Discord Bot?

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/ReportSystemNK#3]
This plugin is already very useful and great! But can you make this plugin can connect with Discord Bot? It will be great when operator can't join the game. Also Discord Bot can make a notification so it will be convenient and easy to know that players who are unable to join as Discord server have a problem. I think it will make this plugin very useful!

**Comment by Mundschutziii** [comment]
Hi,
that would be a good idea, but I'm not very familiar with Discord Bots programming.

**Comment by good777LUCKY** [comment]
Um ... So if you're familiar with the Discord Bot later, can you add it later?

**Comment by Mundschutziii** [comment]
If I know my way around the discord bot area, then yes.
